spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        default_schema: txdb
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5434/txdb?currentSchema=txdb
    username: txdb
    password: txdb
  flyway:
    schemas: txdb
    default-schema: txdb
logging:
  level:
    dev:
      alexengrig:
        tx:
          service: trace
    org:
      springframework:
        transaction: trace
      hibernate:
        type:
          descriptor:
            sql: trace
